### ISSUE TITLE
Se requieren al menos 3 características visibles en el nivel

### ISSUE THREAD

**Issue by edwin-navarrete** [edwin-navarrete/Gadrian#15]
Actualmente sólo se tiene forma del cuerpo y color. Necesitamos agregar otro componente que pienso que es el aditamento de la cabeza:
- Cuernos
- Cabello
- Calvo = Sin cabello ni cuernos

Hay que crear el Trait, el TrairHandler, etc.. Para que el nivel siga teniendo solución, dejaremos a todos "calvos"

**Comment by JhonH3avy** [comment]
El Por ahora el trait ha sido creado y está funcionando, pero faltan las imágenes de los cuernos y el cabello, no cierro el issue, en caso de que algo pueda faltar
